networks:
  default:
    driver: bridge
services:
  nginx:
    build:
      dockerfile: requirements/nginx/Dockerfile
    container_name: nginx
    image: nginx:42
    ports:
      - "80:80"
    volumes:
      - ./web:/var/www/html
    networks:
      - default
    env_file:
      - .env
  wordpress:
    build:
      dockerfile: requirements/wordpress/Dockerfile
    container_name: wordpress
    image: wordpress:42
    volumes:
      - ./web:/var/www/html
    networks:
      - default
    env_file:
      - .env
    secrets:
      - db_user
      - db_pass

  mariadb:
    build: 
      dockerfile: requirements/mariadb/Dockerfile
    container_name: mariadb
    image: mariadb:42
    networks:
      - default
    env_file:
      - .env
    secrets:
      - db_root_pass
      - db_user
      - db_pass

secrets:
  db_user:
    file: ../secrets/db_user.txt
  db_pass:
    file: ../secrets/db_pass.txt
  db_root_pass:
    file: ../secrets/db_root_pass.txt
  wp_admin:
    file: ../secrets/wp_admin.txt
  wp_user_pass:
    file: ../secrets/wp_user_pass.txt