version: "3.3"
networks:
  default:
    driver: bridge

services:
  nginx:
    build:
      context: .
      dockerfile: requirements/nginx/Dockerfile
    container_name: nginx
    image: nginx:42
    ports:
      - "443:443"
    networks:
      - default
    env_file:
      - .env
  wordpress:
    build:
      context: .
      dockerfile: requirements/wordpress/Dockerfile
    container_name: wordpress
    image: wordpress:42
    volumes:
      - /home/cstoia/data/wordpress:/var/www/html
    networks:
      - default
    env_file:
      - .env
    secrets:
      - db_user
      - db_user_password
      - wp_admin_user
      - wp_admin_password
      - wp_admin_email
      - wp_user_name
      - wp_user_password
      - wp_user_email
      - wp_user_role
  mariadb:
    build: 
      context: .
      dockerfile: requirements/mariadb/Dockerfile
    container_name: mariadb
    image: mariadb:42
    volumes:
      - /home/cstoia/data/mariadb:/var/lib/mysql
    networks:
      - default
    env_file:
      - .env
    secrets:
      - db_root_password
      - db_user
      - db_user_password

secrets:
  db_user:
    file: ../secrets/db_user.txt
  db_user_password:
    file: ../secrets/db_user_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  wp_admin_email:
    file: ../secrets/wp_admin_email.txt
  wp_admin_user:
    file: ../secrets/wp_admin_user.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
  wp_user_email:
    file: ../secrets/wp_user_email.txt
  wp_user_name:
    file: ../secrets/wp_user_name.txt
  wp_user_password:
    file: ../secrets/wp_user_password.txt
  wp_user_role:
    file: ../secrets/wp_user_role.txt
  
volumes:
  wordpress:
  mariadb:
