services:
  nginx:
    build:
      dockerfile: requirements/nginx/Dockerfile
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./web:/var/www/html
  wordpress:
    build:
      dockerfile: requirements/wordpress/Dockerfile
    container_name: wordpress
    volumes:
      - ./web:/var/www/html
  mariadb:
    build: 
      dockerfile: requirements/mariadb/Dockerfile
    container_name: mariadb